//! Compression strategies for rolling context.
//!
//! ## Strategies
//!
//! - [`TruncationCompressor`] — Drop oldest messages. Cheap, no model call.
//!   Default for now. Quality: loses all detail about what the user/assistant
//!   said in the early turns.
//!
//! - [`SummaryCompressor`] — Replace evicted messages with a single summary
//!   message. Quality: preserves the gist. The actual LLM call is performed
//!   inline by the proxy (recursively through the same forwarding pipeline)
//!   so the summary comes from a fast/cheap model.
//!
//! - [`HybridCompressor`] — Try summarization first; if it fails, fall back
//!   to truncation. This is the recommended default for production use.
//!
//! ## Why Phase 2 (real LLM summarization) is optional
//!
//! Truncation alone solves the **deadlock** problem (the immediate user pain
//! point). A 200K-token context can be safely truncated to 600K with `truncation`
//! and the conversation continues. The user just loses the earliest turns, which
//! is usually acceptable.
//!
//! LLM summarization preserves *more information* but:
//! - Costs money (one extra request per compression event)
//! - Adds latency (typically 1-3 seconds for a fast model)
//! - Risk: if the summary model is also at-capacity, we're stuck

use crate::proxy::context_roller::context_window::build_summary_placeholder;
use crate::proxy::context_roller::message_store::MessageRecord;
use serde_json::Value;

/// A compression strategy that reduces message history.
pub trait CompressionStrategy: Send + Sync {
    /// Compress `messages_to_compress` into a single replacement message
    /// (or `None` to indicate "no replacement, just delete").
    fn compress(&self, messages_to_compress: &[MessageRecord]) -> Option<Value>;

    /// Human-readable name for logging.
    fn name(&self) -> &'static str;
}

/// Phase 1: Plain truncation — just drop the messages, no replacement.
pub struct TruncationCompressor;

impl CompressionStrategy for TruncationCompressor {
    fn compress(&self, _messages_to_compress: &[MessageRecord]) -> Option<Value> {
        None // no replacement message
    }
    fn name(&self) -> &'static str {
        "truncation"
    }
}

/// Phase 2: Summary placeholder — produces a single message describing that
/// earlier turns were compacted. (A future LLM-backed implementation would
/// replace this with a real summary generated by a cheap model.)
pub struct SummaryCompressor;

impl CompressionStrategy for SummaryCompressor {
    fn compress(&self, messages_to_compress: &[MessageRecord]) -> Option<Value> {
        let evicted_count = messages_to_compress.len();
        let evicted_tokens: u64 = messages_to_compress
            .iter()
            .filter_map(|m| m.token_count)
            .sum();
        let time_range: Option<(i64, i64)> = messages_to_compress
            .iter()
            .filter_map(|m| m.created_at)
            .fold(None, |acc: Option<(i64, i64)>, t| {
                Some(match acc {
                    None => (t, t),
                    Some((s, e)) => (s.min(t), e.max(t)),
                })
            });
        Some(build_summary_placeholder(
            evicted_count,
            evicted_tokens,
            time_range,
        ))
    }
    fn name(&self) -> &'static str {
        "summary-placeholder"
    }
}

/// Recommended production default: try summary, fall back to truncation.
pub struct HybridCompressor {
    primary: Box<dyn CompressionStrategy>,
    fallback: Box<dyn CompressionStrategy>,
}

impl HybridCompressor {
    pub fn new(
        primary: Box<dyn CompressionStrategy>,
        fallback: Box<dyn CompressionStrategy>,
    ) -> Self {
        Self { primary, fallback }
    }
}

impl CompressionStrategy for HybridCompressor {
    fn compress(&self, messages_to_compress: &[MessageRecord]) -> Option<Value> {
        self.primary
            .compress(messages_to_compress)
            .or_else(|| self.fallback.compress(messages_to_compress))
    }
    fn name(&self) -> &'static str {
        "hybrid"
    }
}

/// Get the default compression strategy. Currently `TruncationCompressor` (Phase 1).
/// Switch to `HybridCompressor::new(Box::new(SummaryCompressor), Box::new(TruncationCompressor))`
/// once LLM summarization is wired up.
pub fn default_compressor() -> Box<dyn CompressionStrategy> {
    Box::new(TruncationCompressor)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_records(n: usize) -> Vec<MessageRecord> {
        (0..n)
            .map(|i| MessageRecord {
                id: Some(i as i64),
                session_id: "s".into(),
                role: if i % 2 == 0 { "user" } else { "assistant" }.into(),
                content: format!("content {}", i),
                token_count: Some(50),
                is_summary: false,
                summary_source_ids: Vec::new(),
                created_at: Some(chrono::Utc::now().timestamp() + i as i64),
            })
            .collect()
    }

    #[test]
    fn truncation_compressor_returns_none() {
        let c = TruncationCompressor;
        let result = c.compress(&make_records(5));
        assert!(result.is_none());
        assert_eq!(c.name(), "truncation");
    }

    #[test]
    fn summary_compressor_produces_placeholder() {
        let c = SummaryCompressor;
        let result = c.compress(&make_records(5));
        let v = result.expect("summary should produce a value");
        let content = v["content"].as_str().expect("content field");
        assert!(content.contains("5"));
        assert!(content.contains("Rolling context"));
        assert_eq!(c.name(), "summary-placeholder");
    }

    #[test]
    fn hybrid_falls_back_when_primary_returns_none() {
        // Use a custom primary that always returns None
        struct AlwaysNone;
        impl CompressionStrategy for AlwaysNone {
            fn compress(&self, _: &[MessageRecord]) -> Option<Value> {
                None
            }
            fn name(&self) -> &'static str {
                "always-none"
            }
        }
        let hybrid = HybridCompressor::new(Box::new(AlwaysNone), Box::new(SummaryCompressor));
        let result = hybrid.compress(&make_records(3));
        assert!(result.is_some(), "should fall back to summary");
    }

    #[test]
    fn hybrid_uses_primary_when_available() {
        struct AlwaysSome;
        impl CompressionStrategy for AlwaysSome {
            fn compress(&self, _: &[MessageRecord]) -> Option<Value> {
                Some(serde_json::json!({"role": "user", "content": "primary"}))
            }
            fn name(&self) -> &'static str {
                "always-some"
            }
        }
        let hybrid = HybridCompressor::new(Box::new(AlwaysSome), Box::new(SummaryCompressor));
        let result = hybrid.compress(&make_records(3)).unwrap();
        assert_eq!(result["content"].as_str().unwrap(), "primary");
    }

    #[test]
    fn default_is_truncation() {
        let c = default_compressor();
        assert_eq!(c.name(), "truncation");
    }
}
